//
//  UILabel+Night.m
//  UILabel+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UILabel+Night.h"
#import "DKNightVersionManager.h"
#import <objc/runtime.h>

@interface UILabel ()

@property (nonatomic, strong) NSMutableDictionary<NSString *, DKColorPicker> *pickers;

@end

@implementation UILabel (Night)


- (DKColorPicker)dk_textColor {
    return objc_getAssociatedObject(self, @selector(dk_textColor));
}

- (void)dk_setTextColor:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(dk_textColor), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.textColor = picker(self.dk_manager.themeVersion);
    [self.pickers setValue:[picker copy] forKey:@"setTextColor:"];
}

- (DKColorPicker)dk_shadowColor {
    return objc_getAssociatedObject(self, @selector(dk_shadowColor));
}

- (void)dk_setShadowColor:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(dk_shadowColor), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.shadowColor = picker(self.dk_manager.themeVersion);
    [self.pickers setValue:[picker copy] forKey:@"setShadowColor:"];
}

- (DKColorPicker)dk_highlightedTextColor {
    return objc_getAssociatedObject(self, @selector(dk_highlightedTextColor));
}

- (void)dk_setHighlightedTextColor:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(dk_highlightedTextColor), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.highlightedTextColor = picker(self.dk_manager.themeVersion);
    [self.pickers setValue:[picker copy] forKey:@"setHighlightedTextColor:"];
}


@end
