//
//  UIProgressView+Night.m
//  UIProgressView+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UIProgressView+Night.h"
#import "DKNightVersionManager.h"
#import <objc/runtime.h>

@interface UIProgressView ()

@property (nonatomic, strong) NSMutableDictionary<NSString *, DKColorPicker> *pickers;

@end

@implementation UIProgressView (Night)


- (DKColorPicker)dk_progressTintColor {
    return objc_getAssociatedObject(self, @selector(dk_progressTintColor));
}

- (void)dk_setProgressTintColor:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(dk_progressTintColor), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.progressTintColor = picker(self.dk_manager.themeVersion);
    [self.pickers setValue:[picker copy] forKey:@"setProgressTintColor:"];
}

- (DKColorPicker)dk_trackTintColor {
    return objc_getAssociatedObject(self, @selector(dk_trackTintColor));
}

- (void)dk_setTrackTintColor:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(dk_trackTintColor), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.trackTintColor = picker(self.dk_manager.themeVersion);
    [self.pickers setValue:[picker copy] forKey:@"setTrackTintColor:"];
}


@end
