//
//  UISlider+Night.h
//  UISlider+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

@interface UISlider (Night)

@property (nonatomic, copy, setter = dk_setMinimumTrackTintColor:) DKColorPicker dk_minimumTrackTintColor;
@property (nonatomic, copy, setter = dk_setMaximumTrackTintColor:) DKColorPicker dk_maximumTrackTintColor;
@property (nonatomic, copy, setter = dk_setThumbTintColor:) DKColorPicker dk_thumbTintColor;

@end
