//
//  UIView+Night.h
//  UIView+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

@interface UIView (Night)

@property (nonatomic, copy, setter = dk_setBackgroundColor:) DKColorPicker dk_backgroundColor;
@property (nonatomic, copy, setter = dk_setTintColor:) DKColorPicker dk_tintColor;

@end
